require("dotenv").config();

module.exports = {
  ADMIN_EMAIL: process.env.ADMIN_EMAIL,
  ADMIN_PASSWORD: process.env.ADMIN_PASSWORD,
  MONGO_USERNAME: process.env.MONGODB_USERNAME_ASWATHAMA,
  MONGO_PASSWORD_ASWATHAMA: process.env.MONGODB_PASSWORD_ASWATHAMA,
  MONGO_DATABASE_NAME_ASWATHAMA: process.env.MONGO_DATABASE_NAME_ASWATHAMA,
};
